### ISSUE TITLE
sanitize-html security patch required.

### ISSUE THREAD

**Issue by glend1** [djipco/djipevents#12]
i just checked `npm audit` as was given this. this is a problem for users using `webmidi  >=3.0.0-alpha.1`

````
sanitize-html  <=2.3.1
Severity: moderate
Improper Input Validation in sanitize-html - https://github.com/advisories/GHSA-rjqq-98f6-6j3r
Improper Input Validation in sanitize-html - https://github.com/advisories/GHSA-mjxr-4v3x-q3m4
fix available via `npm audit fix --force`
Will install webmidi@2.5.3, which is a breaking change
node_modules/sanitize-html
  ink-docstrap  >=1.0.0
  Depends on vulnerable versions of sanitize-html
  node_modules/ink-docstrap
    gulp-jsdoc3  *
    Depends on vulnerable versions of ink-docstrap
    node_modules/gulp-jsdoc3
      djipevents  >=1.0.0-a
      Depends on vulnerable versions of gulp-jsdoc3
      node_modules/djipevents
        webmidi  >=3.0.0-alpha.1
        Depends on vulnerable versions of djipevents
        node_modules/webmidi

5 moderate severity vulnerabilities
````

**Comment by djipco** [comment]
I'm sorry but I have completely missed this! I updated all dependencies. Cheers!

**Comment by glend1** [comment]
I think you've only updated it for webmidi v2, i still get the warning on v3, when i do `npm audit fix --force` it downgrades the package. I updated my `package.json` to include v3 and the warning came back.

**Comment by djipco** [comment]
It reverts to using v2.x because v3 relies on gulp-jsdoc3 which is vulnerable. Unfortunately, gulp-jsdoc3 is the latest version so there isn't much I can do. However, gulp-jsdoc3 is a devDependency. This means that it's only used during development (to create documentation) and is not executed during usage of the library.
